version: "3"

networks:
  kong-net:
    driver: bridge

services:
  kong-database:
    image: postgres:9.6
    restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_USER: "authentications"
      POSTGRES_DB: "authentications"
      POSTGRES_PASSWORD: "authentications"
    ports:
      - "5432:5432"
